const fs = require('fs');
const path = '/Users/hongyangchun/WorkBuddy/2026-08-04-11-20-30/index.html';
let html = fs.readFileSync(path, 'utf8');

// 每册核心课标词汇：[word, phonetic, meaning, example]
const WORDS = {
  '7上': [
    ['map','/mæp/','n. 地图','This is a map of China.'],
    ['cup','/kʌp/','n. 杯子','I drink milk from a cup.'],
    ['ruler','/ˈruːlə(r)/','n. 尺子','I need a ruler to draw lines.'],
    ['pen','/pen/','n. 钢笔','My pen is black.'],
    ['pencil','/ˈpensl/','n. 铅笔','Where is my pencil?'],
    ['orange','/ˈɒrɪndʒ/','n./adj. 橙子；橙色的','I eat an orange.'],
    ['jacket','/ˈdʒækɪt/','n. 夹克衫','This jacket is blue.'],
    ['key','/kiː/','n. 钥匙','The key is on the desk.'],
    ['quilt','/kwɪlt/','n. 被子','The quilt is white.'],
    ['it','/ɪt/','pron. 它','It is a dog.'],
    ['this','/ðɪs/','pron. 这；这个','This is my book.'],
    ['that','/ðæt/','pron. 那；那个','That is a car.'],
    ['spell','/spel/','v. 拼写','Can you spell your name?'],
    ['color','/ˈkʌlə(r)/','n. 颜色','What color is it?'],
    ['red','/red/','adj./n. 红色（的）','I like red.'],
    ['yellow','/ˈjeləʊ/','adj./n. 黄色（的）','The banana is yellow.'],
    ['green','/ɡriːn/','adj./n. 绿色（的）','Green is my favorite color.'],
    ['blue','/bluː/','adj./n. 蓝色（的）','The sky is blue.'],
    ['black','/blæk/','adj./n. 黑色（的）','His shoes are black.'],
    ['white','/waɪt/','adj./n. 白色（的）','She wears a white dress.'],
    ['purple','/ˈpɜːpl/','adj./n. 紫色（的）','I have a purple bag.'],
    ['brown','/braʊn/','adj./n. 棕色（的）','The dog is brown.'],
    ['name','/neɪm/','n. 名字','My name is Tom.'],
    ['nice','/naɪs/','adj. 令人愉快的','Nice to meet you.'],
    ['to','/tuː/','prep. 向；朝','Please listen to me.'],
    ['meet','/miːt/','v. 遇见；结识','Glad to meet you.'],
    ['too','/tuː/','adv. 也；又','I like apples, too.'],
    ['your','/jɔː(r)/','pron. 你的；你们的','Is this your book?'],
    ['Ms','/mɪz/','n. 女士','Ms. Smith is our teacher.'],
    ['his','/hɪz/','pron. 他的','His bag is new.'],
    ['and','/ænd/','conj. 和；又','Tom and Jerry.'],
    ['her','/hɜː(r)/','pron. 她的','Her name is Lucy.'],
    ['yes','/jes/','adv. 是的','Yes, I am.'],
    ['she','/ʃiː/','pron. 她','She is a student.'],
    ['he','/hiː/','pron. 他','He is my brother.'],
    ['no','/nəʊ/','adv. 不；没有','No, thanks.'],
    ['not','/nɒt/','adv. 不；没有','He is not here.'],
    ['zero','/ˈzɪərəʊ/','num. 零','Zero is a number.'],
    ['one','/wʌn/','num. 一','I have one book.'],
    ['two','/tuː/','num. 二','Two apples, please.'],
    ['three','/θriː/','num. 三','Three boys are here.'],
    ['four','/fɔː(r)/','num. 四','There are four cats.'],
    ['five','/faɪv/','num. 五','Five pens on the desk.'],
    ['six','/sɪks/','num. 六','Six students in the room.'],
    ['seven','/ˈsevn/','num. 七','Seven days a week.'],
    ['eight','/eɪt/','num. 八','I am eight years old.'],
    ['nine','/naɪn/','num. 九','Nine birds in the tree.'],
    ['phone','/fəʊn/','n. 电话','Call me on my phone.'],
    ['number','/ˈnʌmbə(r)/','n. 号码；数字','What is your number?'],
    ['first','/fɜːst/','adj. 第一','He is first in class.'],
    ['last','/lɑːst/','adj. 最后的','Last name is family name.'],
    ['family','/ˈfæməli/','n. 家庭','I love my family.'],
    ['parent','/ˈpeərənt/','n. 父（母）亲','My parent is a teacher.'],
    ['brother','/ˈbrʌðə(r)/','n. 兄；弟','My brother is tall.'],
    ['grandmother','/ˈɡrænmʌðə(r)/','n. 祖母；外祖母','Grandmother is kind.'],
    ['grandfather','/ˈɡrænfɑːðə(r)/','n. 祖父；外祖父','Grandfather reads books.'],
    ['grandparent','/ˈɡrænpeərənt/','n. 祖父（母）','I visit my grandparents.'],
    ['sister','/ˈsɪstə(r)/','n. 姐；妹','My sister is nine.'],
    ['aunt','/ɑːnt/','n. 姑母；姨母','Aunt Lily is a doctor.'],
    ['uncle','/ˈʌŋkl/','n. 舅父；叔父','Uncle Tom is funny.'],
    ['cousin','/ˈkʌzn/','n. 堂（表）兄弟；姐妹','My cousin is in Beijing.'],
    ['daughter','/ˈdɔːtə(r)/','n. 女儿','They have one daughter.'],
    ['son','/sʌn/','n. 儿子','Her son is a pupil.'],
    ['these','/ðiːz/','pron. 这些','These are my books.'],
    ['those','/ðəʊz/','pron. 那些','Those are buses.'],
    ['who','/huː/','pron. 谁','Who is he?'],
    ['they','/ðeɪ/','pron. 他（她/它）们','They are students.'],
    ['have','/hæv/','v. 有','I have a dog.'],
    ['day','/deɪ/','n. 一天；白天','Have a good day!'],
    ['book','/bʊk/','n. 书','This book is interesting.'],
    ['eraser','/ɪˈreɪzə(r)/','n. 橡皮','I need an eraser.'],
    ['box','/bɒks/','n. 箱；盒','The box is heavy.'],
    ['schoolbag','/ˈskuːlbæɡ/','n. 书包','My schoolbag is red.'],
    ['dictionary','/ˈdɪkʃənri/','n. 词典','Use a dictionary, please.'],
    ['mine','/maɪn/','pron. 我的','The pen is mine.'],
    ['yours','/jɔːz/','pron. 你的；你们的','Is this book yours?'],
    ['teacher','/ˈtiːtʃə(r)/','n. 老师','Our teacher is kind.'],
    ['excuse','/ɪkˈskjuːz/','v. 原谅','Excuse me, where is the door?'],
    ['thank','/θæŋk/','v. 感谢','Thank you very much.'],
    ['about','/əˈbaʊt/','prep. 关于','A book about animals.'],
    ['for','/fɔː(r)/','prep. 为了','This is for you.'],
    ['help','/help/','v./n. 帮助','Can you help me?'],
    ['welcome','/ˈwelkəm/','adj. 受欢迎的','You are welcome.'],
    ['where','/weə(r)/','adv. 在哪里','Where is my cat?'],
    ['table','/ˈteɪbl/','n. 桌子','The book is on the table.'],
    ['bed','/bed/','n. 床','I sleep in my bed.'],
    ['bookcase','/ˈbʊkkeɪs/','n. 书架','Books are in the bookcase.'],
    ['sofa','/ˈsəʊfə/','n. 沙发','The cat is on the sofa.'],
    ['chair','/tʃeə(r)/','n. 椅子','Sit on the chair, please.'],
    ['on','/ɒn/','prep. 在……上','The cup is on the desk.'],
    ['in','/ɪn/','prep. 在……里','The pen is in the box.'],
    ['under','/ˈʌndə(r)/','prep. 在……下','The ball is under the bed.'],
    ['come','/kʌm/','v. 来','Come here, please.'],
    ['desk','/desk/','n. 书桌','My book is on the desk.'],
    ['think','/θɪŋk/','v. 认为；想','I think it is right.'],
    ['room','/ruːm/','n. 房间','This is my room.'],
    ['their','/ðeə(r)/','pron. 他（她/它）们的','Their dog is big.'],
    ['hat','/hæt/','n. 帽子','His hat is new.'],
    ['head','/hed/','n. 头','My head hurts.'],
    ['radio','/ˈreɪdiəʊ/','n. 收音机','He listens to the radio.'],
    ['clock','/klɒk/','n. 时钟','The clock is on the wall.'],
    ['tape','/teɪp/','n. 磁带','I have a tape.'],
    ['player','/ˈpleɪə(r)/','n. 播放机','a tape player'],
    ['model','/ˈmɒdl/','n. 模型','a model plane'],
    ['plane','/pleɪn/','n. 飞机','The plane is white.'],
    ['tidy','/ˈtaɪdi/','adj. 整洁的','Her room is tidy.'],
    ['but','/bʌt/','conj. 但是','I am small but strong.'],
    ['our','/ˈaʊə(r)/','pron. 我们的','This is our school.'],
    ['everywhere','/ˈevriweə(r)/','adv. 到处','Books are everywhere.'],
    ['always','/ˈɔːlweɪz/','adv. 总是','He always helps me.'],
    ['do','/duː/','aux./v. 做','Do you like sports?'],
    ['tennis','/ˈtenɪs/','n. 网球','Let us play tennis.'],
    ['ball','/bɔːl/','n. 球','The ball is red.'],
    ['ping-pong','/ˈpɪŋpɒŋ/','n. 乒乓球','I like ping-pong.'],
    ['soccer','/ˈsɒkə(r)/','n. 足球','He plays soccer.'],
    ['volleyball','/ˈvɒlibɔːl/','n. 排球','We have a volleyball.'],
    ['basketball','/ˈbɑːskɪtbɔːl/','n. 篮球','Basketball is fun.'],
    ['let','/let/','v. 让','Let me help you.'],
    ['us','/ʌs/','pron. 我们','Come with us.'],
    ['go','/ɡəʊ/','v. 去','Let us go to school.'],
    ['we','/wiː/','pron. 我们','We are friends.'],
    ['late','/leɪt/','adj. 迟到','Don\'t be late.'],
    ['great','/ɡreɪt/','adj. 美妙的','That sounds great.'],
    ['play','/pleɪ/','v. 玩耍；打（球）','I play basketball.'],
    ['sound','/saʊnd/','v. 听起来','That sounds good.'],
    ['interesting','/ˈɪntrəstɪŋ/','adj. 有趣的','The book is interesting.'],
    ['boring','/ˈbɔːrɪŋ/','adj. 无聊的','The class is boring.'],
    ['fun','/fʌn/','adj./n. 有趣的；乐趣','Swimming is fun.'],
    ['difficult','/ˈdɪfɪkəlt/','adj. 困难的','Math is difficult.'],
    ['relaxing','/rɪˈlæksɪŋ/','adj. 轻松的','Music is relaxing.'],
    ['easy','/ˈiːzi/','adj. 容易的','English is easy.'],
    ['watch','/wɒtʃ/','v. 观看','I watch TV at night.'],
    ['TV','/ˌtiː ˈviː/','n. 电视','The TV is new.'],
    ['same','/seɪm/','adj. 相同的','We are in the same class.'],
    ['love','/lʌv/','v. 爱；喜爱','I love my dog.'],
    ['with','/wɪð/','prep. 和……一起','I play with Tom.'],
    ['sport','/spɔːt/','n. 体育运动','Soccer is my favorite sport.'],
    ['them','/ðem/','pron. 他（她/它）们','I like them.'],
    ['only','/ˈəʊnli/','adv. 只；仅','I have only one pen.'],
    ['like','/laɪk/','v. 喜欢','I like apples.'],
    ['after','/ˈɑːftə(r)/','prep. 在……以后','After school, I play.'],
    ['class','/klɑːs/','n. 班级；课','We are in the same class.'],
    ['classmate','/ˈklɑːsmeɪt/','n. 同班同学','He is my classmate.'],
    ['banana','/bəˈnɑːnə/','n. 香蕉','I eat a banana.'],
    ['hamburger','/ˈhæmbɜːɡə(r)/','n. 汉堡包','A hamburger for lunch.'],
    ['tomato','/təˈmɑːtəʊ/','n. 西红柿','I like tomatoes.'],
    ['ice-cream','/ˈaɪskriːm/','n. 冰淇淋','Ice-cream is cold.'],
    ['salad','/ˈsæləd/','n. 沙拉','Vegetable salad is healthy.'],
    ['strawberry','/ˈstrɔːbəri/','n. 草莓','Strawberries are red.'],
    ['pear','/peə(r)/','n. 梨','A pear is sweet.'],
    ['milk','/mɪlk/','n. 牛奶','I drink milk every day.'],
    ['bread','/bred/','n. 面包','I eat bread for breakfast.'],
    ['birthday','/ˈbɜːθdeɪ/','n. 生日','Happy birthday!'],
    ['dinner','/ˈdɪnə(r)/','n. 晚餐','We eat dinner at 7.'],
    ['week','/wiːk/','n. 周；星期','There are 7 days in a week.'],
    ['food','/fuːd/','n. 食物','Healthy food is good.'],
    ['vegetable','/ˈvedʒtəbl/','n. 蔬菜','Eat more vegetables.'],
    ['fruit','/fruːt/','n. 水果','Fruit is sweet.'],
    ['apple','/ˈæpl/','n. 苹果','An apple a day.'],
    ['egg','/eɡ/','n. 蛋','I eat an egg.'],
    ['carrot','/ˈkærət/','n. 胡萝卜','Carrots are orange.'],
    ['rice','/raɪs/','n. 大米','I eat rice.'],
    ['chicken','/ˈtʃɪkɪn/','n. 鸡肉；小鸡','I like chicken.'],
    ['breakfast','/ˈbrekfəst/','n. 早餐','I eat eggs for breakfast.'],
    ['lunch','/lʌntʃ/','n. 午餐','Lunch is at 12.'],
    ['star','/stɑː(r)/','n. 星星','The stars are bright.'],
    ['eat','/iːt/','v. 吃','We eat at home.'],
    ['habit','/ˈhæbɪt/','n. 习惯','Reading is a good habit.'],
    ['healthy','/ˈhelθi/','adj. 健康的','We are healthy.'],
    ['really','/ˈriːəli/','adv. 真正地','That is really good.'],
    ['question','/ˈkwestʃən/','n. 问题','I have a question.'],
    ['want','/wɒnt/','v. 想要','I want a book.'],
    ['fat','/fæt/','adj. 肥的；胖的','The cat is fat.']
  ],
  '7下': [
    ['guitar','/ɡɪˈtɑː(r)/','n. 吉他','I can play the guitar.'],
    ['sing','/sɪŋ/','v. 唱歌','She likes to sing.'],
    ['swim','/swɪm/','v. 游泳','I can swim.'],
    ['dance','/dɑːns/','v. 跳舞','They dance well.'],
    ['draw','/drɔː/','v. 画','I draw a cat.'],
    ['chess','/tʃes/','n. 国际象棋','Let us play chess.'],
    ['speak','/spiːk/','v. 说（语言）','Can you speak English?'],
    ['join','/dʒɔɪn/','v. 参加；加入','Join our club!'],
    ['club','/klʌb/','n. 俱乐部','I am in the art club.'],
    ['tell','/tel/','v. 告诉','Tell me a story.'],
    ['story','/ˈstɔːri/','n. 故事','I read a story.'],
    ['write','/raɪt/','v. 写','I write a letter.'],
    ['show','/ʃəʊ/','n./v. 演出；展示','Show me your book.'],
    ['talk','/tɔːk/','v. 说话','We talk in English.'],
    ['kung fu','/ˌkʌŋ ˈfuː/','n. 功夫','He does kung fu.'],
    ['drum','/drʌm/','n. 鼓','Play the drums.'],
    ['piano','/piˈænəʊ/','n. 钢琴','She plays the piano.'],
    ['violin','/ˌvaɪəˈlɪn/','n. 小提琴','He plays the violin.'],
    ['people','/ˈpiːpl/','n. 人；人们','Many people here.'],
    ['home','/həʊm/','n. 家','I go home at 5.'],
    ['make','/meɪk/','v. 使；制作','Make a cake, please.'],
    ['today','/təˈdeɪ/','n./adv. 今天','Today is sunny.'],
    ['center','/ˈsentə(r)/','n. 中心','the music center'],
    ['weekend','/ˌwiːkˈend/','n. 周末','I am free on the weekend.'],
    ['teach','/tiːtʃ/','v. 教','She teaches English.'],
    ['musician','/mjuˈzɪʃn/','n. 音乐家','He is a musician.'],
    ['up','/ʌp/','adv. 向上','Get up, please.'],
    ['get up','/ɡet ʌp/','phr. 起床','I get up at 7.'],
    ['dress','/dres/','v. 穿衣服','Dress quickly!'],
    ['brush','/brʌʃ/','v. 刷','Brush your teeth.'],
    ['tooth','/tuːθ/','n. 牙齿','I brush my teeth.'],
    ['shower','/ˈʃaʊə(r)/','n. 淋浴','take a shower'],
    ['usually','/ˈjuːʒuəli/','adv. 通常','I usually read at night.'],
    ['forty','/ˈfɔːti/','num. 四十','Forty students.'],
    ['fifty','/ˈfɪfti/','num. 五十','Fifty books.'],
    ['never','/ˈnevə(r)/','adv. 从不','I never eat late.'],
    ['early','/ˈɜːli/','adj./adv. 早','Get up early.'],
    ['job','/dʒɒb/','n. 工作','My father has a good job.'],
    ['work','/wɜːk/','v./n. 工作','He works in a school.'],
    ['station','/ˈsteɪʃn/','n. 车站','the bus station'],
    ['o\'clock','/əˈklɒk/','adv. ……点钟','It is 7 o\'clock.'],
    ['night','/naɪt/','n. 夜晚','Good night!'],
    ['funny','/ˈfʌni/','adj. 有趣的','The story is funny.'],
    ['exercise','/ˈeksəsaɪz/','v./n. 锻炼','I exercise every day.'],
    ['best','/best/','adj. 最好的','Best friend.'],
    ['group','/ɡruːp/','n. 组；群','a group of students'],
    ['half','/hɑːf/','n. 一半','half past six'],
    ['past','/pɑːst/','prep. 过（时间）','half past seven'],
    ['quarter','/ˈkwɔːtə(r)/','n. 一刻钟','a quarter to eight'],
    ['homework','/ˈhəʊmwɜːk/','n. 家庭作业','I do my homework.'],
    ['run','/rʌn/','v. 跑','I run in the morning.'],
    ['clean','/kliːn/','adj./v. 干净的；打扫','Clean your room.'],
    ['walk','/wɔːk/','v. 行走','I walk to school.'],
    ['quickly','/ˈkwɪkli/','adv. 很快地','He runs quickly.'],
    ['train','/treɪn/','n. 火车','by train'],
    ['bus','/bʌs/','n. 公共汽车','I take the bus.'],
    ['subway','/ˈsʌbweɪ/','n. 地铁','the subway station'],
    ['ride','/raɪd/','v. 骑','I ride a bike.'],
    ['bike','/baɪk/','n. 自行车','My bike is new.'],
    ['sixty','/ˈsɪksti/','num. 六十','Sixty minutes.'],
    ['seventy','/ˈsevnti/','num. 七十','Seventy books.'],
    ['eighty','/ˈeɪti/','num. 八十','Eighty students.'],
    ['ninety','/ˈnaɪnti/','num. 九十','Ninety pages.'],
    ['hundred','/ˈhʌndrəd/','num. 一百','one hundred'],
    ['minute','/ˈmɪnɪt/','n. 分钟','ten minutes'],
    ['far','/fɑː(r)/','adj. 远的','The school is far.'],
    ['kilometer','/ˈkɪləmiːtə(r)/','n. 千米','two kilometers'],
    ['new','/njuː/','adj. 新的','a new book'],
    ['every','/ˈevri/','adj. 每一','every day'],
    ['by','/baɪ/','prep. 由；乘','by bus'],
    ['drive','/draɪv/','v. 驾驶','My dad drives to work.'],
    ['car','/kɑː(r)/','n. 小汽车','The car is red.'],
    ['live','/lɪv/','v. 居住','I live in Beijing.'],
    ['stop','/stɒp/','n./v. 车站；停止','Bus stop.'],
    ['cross','/krɒs/','v. 横过','Cross the street.'],
    ['river','/ˈrɪvə(r)/','n. 河','The river is long.'],
    ['many','/ˈmeni/','adj. 许多','many students'],
    ['village','/ˈvɪlɪdʒ/','n. 村庄','a small village'],
    ['bridge','/brɪdʒ/','n. 桥','a long bridge'],
    ['boat','/bəʊt/','n. 小船','by boat'],
    ['year','/jɪə(r)/','n. 年','This year is 2026.'],
    ['afraid','/əˈfreɪd/','adj. 害怕','I am afraid of dogs.'],
    ['between','/bɪˈtwiːn/','prep. 在……之间','between two trees'],
    ['leave','/liːv/','v. 离开','Leave home at 7.'],
    ['dream','/driːm/','n. 梦想','My dream is big.'],
    ['true','/truː/','adj. 真的','That is true.'],
    ['rule','/ruːl/','n. 规则','School rules.'],
    ['arrive','/əˈraɪv/','v. 到达','Arrive at school.'],
    ['hallway','/ˈhɔːlweɪ/','n. 走廊','in the hallway'],
    ['listen','/ˈlɪsn/','v. 听','Listen to me.'],
    ['fight','/faɪt/','v. 打架','Don\'t fight.'],
    ['sorry','/ˈsɒri/','adj. 抱歉的','I am sorry.'],
    ['outside','/ˌaʊtˈsaɪd/','adv. 在外面','Go outside.'],
    ['wear','/weə(r)/','v. 穿；戴','Wear your coat.'],
    ['important','/ɪmˈpɔːtnt/','adj. 重要的','This is important.'],
    ['bring','/brɪŋ/','v. 带来','Bring your book.'],
    ['require','/rɪˈkwaɪə(r)/','v. 需要','We require quiet.'],
    ['uniform','/ˈjuːnɪfɔːm/','n. 制服','a school uniform'],
    ['quiet','/ˈkwaɪət/','adj. 安静的','Be quiet, please.'],
    ['dish','/dɪʃ/','n. 碟；盘','Do the dishes.'],
    ['before','/bɪˈfɔː(r)/','prep. 在……以前','before class'],
    ['dirty','/ˈdɜːti/','adj. 脏的','The room is dirty.'],
    ['kitchen','/ˈkɪtʃɪn/','n. 厨房','in the kitchen'],
    ['more','/mɔː(r)/','adj./adv. 更多的','more books'],
    ['noisy','/ˈnɔɪzi/','adj. 吵闹的','The room is noisy.'],
    ['relax','/rɪˈlæks/','v. 放松','Relax at home.'],
    ['read','/riːd/','v. 读','I read books.'],
    ['terrible','/ˈterəbl/','adj. 糟糕的','The weather is terrible.'],
    ['feel','/fiːl/','v. 感受','I feel happy.'],
    ['strict','/strɪkt/','adj. 严格的','My teacher is strict.'],
    ['remember','/rɪˈmembə(r)/','v. 记得','Remember my words.'],
    ['follow','/ˈfɒləʊ/','v. 遵循','Follow the rules.'],
    ['luck','/lʌk/','n. 运气','Good luck!'],
    ['panda','/ˈpændə/','n. 熊猫','The panda is cute.'],
    ['zoo','/zuː/','n. 动物园','We go to the zoo.'],
    ['tiger','/ˈtaɪɡə(r)/','n. 老虎','The tiger is big.'],
    ['elephant','/ˈelɪfənt/','n. 大象','An elephant is strong.'],
    ['koala','/kəʊˈɑːlə/','n. 考拉','Koalas sleep a lot.'],
    ['lion','/ˈlaɪən/','n. 狮子','The lion is scary.'],
    ['giraffe','/dʒəˈrɑːf/','n. 长颈鹿','A giraffe is tall.'],
    ['animal','/ˈænɪml/','n. 动物','I like animals.'],
    ['cute','/kjuːt/','adj. 可爱的','The dog is cute.'],
    ['lazy','/ˈleɪzi/','adj. 懒的','The cat is lazy.'],
    ['smart','/smɑːt/','adj. 聪明的','He is smart.'],
    ['beautiful','/ˈbjuːtɪfl/','adj. 美丽的','A beautiful flower.'],
    ['scary','/ˈskeəri/','adj. 吓人的','The movie is scary.'],
    ['kind','/kaɪnd/','n. 种类','What kind of animal?'],
    ['Australia','/ɒˈstreɪliə/','n. 澳大利亚','Koalas are from Australia.'],
    ['south','/saʊθ/','n. 南；南方','in the south'],
    ['Africa','/ˈæfrɪkə/','n. 非洲','Lions are from Africa.'],
    ['pet','/pet/','n. 宠物','My pet is a cat.'],
    ['leg','/leɡ/','n. 腿','The dog has four legs.'],
    ['cat','/kæt/','n. 猫','A small cat.'],
    ['sleep','/sliːp/','v. 睡觉','I sleep at 9.'],
    ['friendly','/ˈfrendli/','adj. 友好的','He is friendly.'],
    ['shy','/ʃaɪ/','adj. 害羞的','The girl is shy.'],
    ['save','/seɪv/','v. 拯救','Save the animals.'],
    ['symbol','/ˈsɪmbl/','n. 象征','a symbol of good luck'],
    ['flag','/flæɡ/','n. 旗','the national flag'],
    ['forget','/fəˈɡet/','v. 忘记','Don\'t forget your book.'],
    ['place','/pleɪs/','n. 地点','a quiet place'],
    ['water','/ˈwɔːtə(r)/','n. 水','Drink water.'],
    ['danger','/ˈdeɪndʒə(r)/','n. 危险','in danger'],
    ['cut','/kʌt/','v. 砍；切','Cut the tree.'],
    ['down','/daʊn/','adv. 向下','Sit down.'],
    ['tree','/triː/','n. 树','a tall tree'],
    ['kill','/kɪl/','v. 杀死','Don\'t kill animals.'],
    ['over','/ˈəʊvə(r)/','prep. 超过','over 100'],
    ['ivory','/ˈaɪvəri/','n. 象牙','No ivory trade.'],
    ['newspaper','/ˈnjuːzpeɪpə(r)/','n. 报纸','read a newspaper'],
    ['use','/juːz/','v. 使用','Use a pen.'],
    ['soup','/suːp/','n. 汤','make soup'],
    ['wash','/wɒʃ/','v. 洗','Wash your hands.'],
    ['movie','/ˈmuːvi/','n. 电影','go to the movies'],
    ['just','/dʒʌst/','adv. 只是；恰好','I just watch TV.'],
    ['eat out','/iːt aʊt/','phr. 出去吃饭','Let us eat out.'],
    ['house','/haʊs/','n. 房子','a big house'],
    ['drink','/drɪŋk/','v. 喝','Drink some water.'],
    ['tea','/tiː/','n. 茶','drink tea'],
    ['tomorrow','/təˈmɒrəʊ/','n. 明天','See you tomorrow.'],
    ['pool','/puːl/','n. 游泳池','a swimming pool'],
    ['shop','/ʃɒp/','v. 购物','I shop on Sunday.'],
    ['supermarket','/ˈsuːpəmɑːkɪt/','n. 超市','Go to the supermarket.'],
    ['man','/mæn/','n. 男人','a young man'],
    ['race','/reɪs/','n. 竞赛','a boat race'],
    ['study','/ˈstʌdi/','v. 学习','I study English.'],
    ['state','/steɪt/','n. 州','the United States'],
    ['American','/əˈmerɪkən/','adj. 美国的','American food'],
    ['dragon','/ˈdræɡən/','n. 龙','a dragon boat'],
    ['other','/ˈʌðə(r)/','adj. 其他的','other students'],
    ['young','/jʌŋ/','adj. 年轻的','a young man'],
    ['child','/tʃaɪld/','n. 儿童','a young child'],
    ['miss','/mɪs/','v. 想念','I miss my dog.'],
    ['wish','/wɪʃ/','v. 希望','I wish to go.'],
    ['delicious','/dɪˈlɪʃəs/','adj. 美味的','The food is delicious.'],
    ['still','/stɪl/','adv. 仍然','I am still here.']
  ],
  '8上': [
    ['anyone','/ˈeniwʌn/','pron. 任何人','Is anyone here?'],
    ['anywhere','/ˈeniweə(r)/','adv. 任何地方','Go anywhere you like.'],
    ['wonderful','/ˈwʌndəfl/','adj. 精彩的','The trip is wonderful.'],
    ['few','/fjuː/','adj. 很少的','a few friends'],
    ['quite a few','/kwaɪt ə fjuː/','phr. 相当多','quite a few books'],
    ['most','/məʊst/','adj./adv. 最多','most students'],
    ['something','/ˈsʌmθɪŋ/','pron. 某事','Something is wrong.'],
    ['nothing','/ˈnʌθɪŋ/','pron. 没有什么','Nothing to do.'],
    ['everyone','/ˈevriwʌn/','pron. 每人','Everyone is here.'],
    ['myself','/maɪˈself/','pron. 我自己','I do it myself.'],
    ['yourself','/jɔːˈself/','pron. 你自己','Enjoy yourself.'],
    ['hen','/hen/','n. 母鸡','a fat hen'],
    ['pig','/pɪɡ/','n. 猪','The pig is big.'],
    ['seem','/siːm/','v. 好像','It seems easy.'],
    ['bored','/bɔːd/','adj. 无聊的','I am bored.'],
    ['someone','/ˈsʌmwʌn/','pron. 某人','Someone is at the door.'],
    ['diary','/ˈdaɪəri/','n. 日记','Keep a diary.'],
    ['activity','/ækˈtɪvəti/','n. 活动','after-school activities'],
    ['decide','/dɪˈsaɪd/','v. 决定','Decide to go.'],
    ['try','/traɪ/','v. 尝试','Try your best.'],
    ['paragliding','/ˈpærəɡlaɪdɪŋ/','n. 滑翔伞','go paragliding'],
    ['bird','/bɜːd/','n. 鸟','A small bird.'],
    ['bicycle','/ˈbaɪsɪkl/','n. 自行车','ride a bicycle'],
    ['building','/ˈbɪldɪŋ/','n. 建筑物','a tall building'],
    ['trader','/ˈtreɪdə(r)/','n. 商人','a tea trader'],
    ['wonder','/ˈwʌndə(r)/','v. 想知道','I wonder why.'],
    ['difference','/ˈdɪfrəns/','n. 差别','a big difference'],
    ['top','/tɒp/','n. 顶部','at the top'],
    ['wait','/weɪt/','v. 等待','Wait for me.'],
    ['umbrella','/ʌmˈbrelə/','n. 伞','Take an umbrella.'],
    ['wet','/wet/','adj. 湿的','My shoes are wet.'],
    ['because','/bɪˈkɒz/','conj. 因为','I am late because of rain.'],
    ['enough','/ɪˈnʌf/','adj./adv. 足够的','good enough'],
    ['hungry','/ˈhʌŋɡri/','adj. 饥饿的','I am hungry.'],
    ['as','/æz/','prep. 像……一样','as big as'],
    ['hill','/hɪl/','n. 小山','on the hill'],
    ['duck','/dʌk/','n. 鸭','a white duck'],
    ['dislike','/dɪsˈlaɪk/','v. 不喜欢','I dislike rain.'],
    ['housework','/ˈhaʊswɜːk/','n. 家务','do housework'],
    ['hardly','/ˈhɑːdli/','adv. 几乎不','I hardly eat out.'],
    ['ever','/ˈevə(r)/','adv. 曾经','Have you ever been there?'],
    ['hard','/hɑːd/','adv./adj. 努力；硬的','work hard'],
    ['once','/wʌns/','adv. 一次','once a week'],
    ['twice','/twaɪs/','adv. 两次','twice a month'],
    ['Internet','/ˈɪntənet/','n. 互联网','on the Internet'],
    ['program','/ˈprəʊɡræm/','n. 节目','a TV program'],
    ['full','/fʊl/','adj. 满的','a full box'],
    ['swing','/swɪŋ/','n. 秋千','play on the swing'],
    ['maybe','/ˈmeɪbi/','adv. 也许','Maybe it is true.'],
    ['least','/liːst/','adj. 最少的','at least'],
    ['junk','/dʒʌŋk/','n. 无用的东西','junk food'],
    ['coffee','/ˈkɒfi/','n. 咖啡','a cup of coffee'],
    ['health','/helθ/','n. 健康','in good health'],
    ['percent','/pəˈsent/','n. 百分之……','twenty percent'],
    ['online','/ˌɒnˈlaɪn/','adj. 在线的','online shopping'],
    ['although','/ɔːlˈðəʊ/','conj. 虽然','Although it is late.'],
    ['through','/θruː/','prep. 穿过','walk through'],
    ['mind','/maɪnd/','n. 头脑','make up one\'s mind'],
    ['body','/ˈbɒdi/','n. 身体','a healthy body'],
    ['such','/sʌtʃ/','adj. 这样的','such as'],
    ['together','/təˈɡeðə(r)/','adv. 一起','play together'],
    ['die','/daɪ/','v. 死亡','Plants die without water.'],
    ['writer','/ˈraɪtə(r)/','n. 作者','a famous writer'],
    ['dentist','/ˈdentɪst/','n. 牙医','see the dentist'],
    ['magazine','/ˌmæɡəˈziːn/','n. 杂志','a weekly magazine'],
    ['however','/haʊˈevə(r)/','adv. 然而','It is late; however, I wait.'],
    ['than','/ðæn/','prep. 比','taller than'],
    ['more than','/mɔːr ðæn/','phr. 多于','more than ten'],
    ['almost','/ˈɔːlməʊst/','adv. 几乎','almost ready'],
    ['none','/nʌn/','pron. 没有一个','None of them.'],
    ['less','/les/','adj./adv. 更少的','less water'],
    ['point','/pɔɪnt/','n. 得分；点','a key point'],
    ['matter','/ˈmætə(r)/','n. 事情','What is the matter?'],
    ['tummy','/ˈtʌmi/','n. 肚子','My tummy hurts.'],
    ['sore','/sɔː(r)/','adj. 疼痛的','a sore throat'],
    ['stomachache','/ˈstʌməkeɪk/','n. 胃痛','I have a stomachache.'],
    ['foot','/fʊt/','n. 脚','My foot hurts.'],
    ['neck','/nek/','n. 脖子','My neck is sore.'],
    ['stomach','/ˈstʌmək/','n. 胃','My stomach hurts.'],
    ['fever','/ˈfiːvə(r)/','n. 发烧','have a fever'],
    ['lie','/laɪ/','v. 躺','Lie down and rest.'],
    ['rest','/rest/','v. 休息','Have a rest.'],
    ['cough','/kɒf/','n./v. 咳嗽','I cough at night.'],
    ['X-ray','/ˈeks reɪ/','n. X光','take an X-ray'],
    ['toothache','/ˈtuːθeɪk/','n. 牙痛','I have a toothache.'],
    ['headache','/ˈhedeɪk/','n. 头痛','a bad headache'],
    ['break','/breɪk/','v. 弄破','I break my leg.'],
    ['hurt','/hɜːt/','v. 受伤','My arm hurts.'],
    ['passenger','/ˈpæsɪndʒə(r)/','n. 乘客','a bus passenger'],
    ['off','/ɒf/','adv. 离开','get off'],
    ['onto','/ˈɒntu/','prep. 到……上','jump onto'],
    ['trouble','/ˈtrʌbl/','n. 麻烦','in trouble'],
    ['hit','/hɪt/','v. 撞','The car hits a tree.'],
    ['herself','/hɜːˈself/','pron. 她自己','She does it herself.'],
    ['volunteer','/ˌvɒlənˈtɪə(r)/','n. 志愿者','a young volunteer'],
    ['dead','/ded/','adj. 死的','a dead tree'],
    ['risk','/rɪsk/','n. 风险','take a risk'],
    ['situation','/ˌsɪtʃuˈeɪʃn/','n. 情况','a bad situation'],
    ['kilo','/ˈkiːləʊ/','n. 千克','two kilos'],
    ['rock','/rɒk/','n. 岩石','a big rock'],
    ['knife','/naɪf/','n. 刀','a small knife'],
    ['blood','/blʌd/','n. 血','lose blood'],
    ['mean','/miːn/','v. 意思是','What does it mean?'],
    ['importance','/ɪmˈpɔːtns/','n. 重要性','the importance of health'],
    ['decision','/dɪˈsɪʒn/','n. 决定','make a decision'],
    ['control','/kənˈtrəʊl/','n./v. 控制','under control'],
    ['spirit','/ˈspɪrɪt/','n. 勇气','a brave spirit'],
    ['death','/deθ/','n. 死亡','His death is sad.'],
    ['accident','/ˈæksɪdənt/','n. 事故','a car accident'],
    ['bandage','/ˈbændɪdʒ/','n. 绷带','a clean bandage'],
    ['press','/pres/','v. 压','Press here.']
  ],
  '8下': [
    ['neighbor','/ˈneɪbə(r)/','n. 邻居','My neighbor is kind.'],
    ['throw','/θrəʊ/','v. 扔','Throw the ball.'],
    ['neither','/ˈnaɪðə(r)/','pron. 两者都不','Neither is right.'],
    ['borrow','/ˈbɒrəʊ/','v. 借入','Borrow a book.'],
    ['lend','/lend/','v. 借出','Lend me your pen.'],
    ['finger','/ˈfɪŋɡə(r)/','n. 手指','a long finger'],
    ['shirt','/ʃɜːt/','n. 衬衫','a white shirt'],
    ['while','/waɪl/','conj. 当……时候','While I read, he writes.'],
    ['stress','/stres/','n. 压力','under stress'],
    ['waste','/weɪst/','v. 浪费','Don\'t waste water.'],
    ['provide','/prəˈvaɪd/','v. 提供','Provide food.'],
    ['anyway','/ˈeniweɪ/','adv. 无论如何','Anyway, let us go.'],
    ['depend','/dɪˈpend/','v. 依靠','Depend on you.'],
    ['develop','/dɪˈveləp/','v. 发展','Develop a habit.'],
    ['fair','/feə(r)/','adj. 公平的','That is fair.'],
    ['unfair','/ˌʌnˈfeə(r)/','adj. 不公平的','That is unfair.'],
    ['robot','/ˈrəʊbɒt/','n. 机器人','a small robot'],
    ['repair','/rɪˈpeə(r)/','v. 修理','Repair the bike.'],
    ['fix','/fɪks/','v. 修理','Fix the clock.'],
    ['broken','/ˈbrəʊkən/','adj. 破损的','a broken chair'],
    ['wheel','/wiːl/','n. 轮子','a bike wheel'],
    ['letter','/ˈletə(r)/','n. 信','a long letter'],
    ['disabled','/dɪsˈeɪbld/','adj. 残疾的','a disabled man'],
    ['blind','/blaɪnd/','adj. 盲的','a blind dog'],
    ['deaf','/def/','adj. 聋的','a deaf girl'],
    ['imagine','/ɪˈmædʒɪn/','v. 想象','Imagine a world.'],
    ['difficulty','/ˈdɪfɪkəlti/','n. 困难','a big difficulty'],
    ['open','/ˈəʊpən/','v. 打开','Open the door.'],
    ['door','/dɔː(r)/','n. 门','Close the door.'],
    ['carry','/ˈkæri/','v. 拿；搬','Carry the box.'],
    ['train','/treɪn/','v. 训练','Train a dog.'],
    ['excited','/ɪkˈsaɪtɪd/','adj. 激动的','I am excited.'],
    ['kindness','/ˈkaɪndnəs/','n. 仁慈','a act of kindness'],
    ['clever','/ˈklevə(r)/','adj. 聪明的','a clever boy'],
    ['understand','/ˌʌndəˈstænd/','v. 理解','I understand you.'],
    ['change','/tʃeɪndʒ/','v./n. 改变','Change your plan.'],
    ['interested','/ˈɪntrəstɪd/','adj. 感兴趣的','I am interested in art.'],
    ['sir','/sɜː(r)/','n. 先生','Yes, sir.'],
    ['madam','/ˈmædəm/','n. 夫人','Excuse me, madam.'],
    ['junk','/dʒʌŋk/','adj. 无用的','junk mail'],
    ['treasure','/ˈtreʒə(r)/','n. 宝物','a hidden treasure'],
    ['island','/ˈaɪlənd/','n. 岛','a small island'],
    ['classic','/ˈklæsɪk/','n. 名著','a literary classic'],
    ['page','/peɪdʒ/','n. 页','page ten'],
    ['hurry','/ˈhʌri/','v. 匆忙','Hurry up!'],
    ['ship','/ʃɪp/','n. 船','a big ship'],
    ['tool','/tuːl/','n. 工具','a useful tool'],
    ['gun','/ɡʌn/','n. 枪','a toy gun'],
    ['mark','/mɑːk/','n. 迹象','a mark on the wall'],
    ['sand','/sænd/','n. 沙','on the sand'],
    ['cannibal','/ˈkænɪbl/','n. 食人族','a cannibal tribe'],
    ['towards','/təˈwɔːdz/','prep. 朝','towards the door'],
    ['land','/lænd/','n. 陆地','on land'],
    ['fiction','/ˈfɪkʃn/','n. 小说','science fiction'],
    ['technology','/tekˈnɒlədʒi/','n. 科技','modern technology'],
    ['French','/frentʃ/','adj. 法国的','French food'],
    ['pop','/pɒp/','adj. 流行的','pop music'],
    ['rock','/rɒk/','n. 摇滚乐','rock and roll'],
    ['band','/bænd/','n. 乐队','a music band'],
    ['forever','/fərˈevə(r)/','adv. 永远','love forever'],
    ['abroad','/əˈbrɔːd/','adv. 在国外','study abroad'],
    ['fan','/fæn/','n. 迷','a football fan'],
    ['southern','/ˈsʌðən/','adj. 南方的','southern China'],
    ['modern','/ˈmɒdn/','adj. 现代的','modern art'],
    ['success','/səkˈses/','n. 成功','a big success'],
    ['belong','/bɪˈlɒŋ/','v. 属于','Belong to me.'],
    ['beauty','/ˈbjuːti/','n. 美','the beauty of nature'],
    ['record','/ˈrekɔːd/','n. 唱片','a music record'],
    ['line','/laɪn/','n. 行；线','Wait in line.'],
    ['camera','/ˈkæmərə/','n. 照相机','a new camera'],
    ['tent','/tent/','n. 帐篷','a small tent'],
    ['nature','/ˈneɪtʃə(r)/','n. 大自然','love nature'],
    ['beach','/biːtʃ/','n. 海滩','on the beach'],
    ['mouse','/maʊs/','n. 老鼠','a little mouse'],
    ['baby','/ˈbeɪbi/','n. 婴儿','a crying baby'],
    ['language','/ˈlæŋɡwɪdʒ/','n. 语言','a foreign language'],
    ['fox','/fɒks/','n. 狐狸','a clever fox'],
    ['forest','/ˈfɒrɪst/','n. 森林','a dark forest'],
    ['protect','/prəˈtekt/','v. 保护','Protect the earth.'],
    ['furniture','/ˈfɜːnɪtʃə(r)/','n. 家具','a piece of furniture'],
    ['research','/rɪˈsɜːtʃ/','n. 研究','do research'],
    ['government','/ˈɡʌvənmənt/','n. 政府','the government'],
    ['member','/ˈmembə(r)/','n. 成员','a family member'],
    ['conditions','/kənˈdɪʃnz/','n. 条件','living conditions'],
    ['birth','/bɜːθ/','n. 出生','date of birth'],
    ['keeper','/ˈkiːpə(r)/','n. 饲养员','a panda keeper'],
    ['bamboo','/ˌbæmˈbuː/','n. 竹子','Pandas eat bamboo.'],
    ['awake','/əˈweɪk/','adj. 醒着的','I am awake.'],
    ['illness','/ˈɪlnəs/','n. 疾病','a serious illness'],
    ['wild','/waɪld/','adj. 野生的','wild animals'],
    ['oil','/ɔɪl/','n. 油','cooking oil'],
    ['protection','/prəˈtekʃn/','n. 保护','environmental protection'],
    ['huge','/hjuːdʒ/','adj. 巨大的','a huge tree'],
    ['southwest','/ˌsaʊθˈwest/','n. 西南','in the southwest'],
    ['tour','/tʊə(r)/','n. 旅行','a city tour'],
    ['include','/ɪnˈkluːd/','v. 包括','The price includes tax.'],
    ['freeze','/friːz/','v. 冻结','Water freezes.'],
    ['achievement','/əˈtʃiːvmənt/','n. 成就','a great achievement'],
    ['challenge','/ˈtʃælɪndʒ/','n. 挑战','face a challenge'],
    ['in the face of','/ɪn ðə feɪs ɒv/','phr. 面对','in the face of danger'],
    ['force','/fɔːs/','n. 力','a strong force'],
    ['even','/ˈiːvn/','adv. 甚至','even better'],
    ['sea','/siː/','n. 海','the deep sea'],
    ['low','/ləʊ/','adj. 低的','a low price'],
    ['step','/step/','n. 台阶','a stone step']
  ],
  '9上': [
    ['textbook','/ˈtekstbʊk/','n. 教科书','a new textbook'],
    ['conversation','/ˌkɒnvəˈseɪʃn/','n. 交谈','a long conversation'],
    ['aloud','/əˈlaʊd/','adv. 大声地','Read aloud.'],
    ['pronounce','/prəˈnaʊns/','v. 发音','Pronounce carefully.'],
    ['sentence','/ˈsentəns/','n. 句子','a long sentence'],
    ['patient','/ˈpeɪʃnt/','adj. 有耐心的','Be patient.'],
    ['expression','/ɪkˈspreʃn/','n. 表达','a facial expression'],
    ['discover','/dɪˈskʌvə(r)/','v. 发现','Discover a secret.'],
    ['secret','/ˈsiːkrət/','n. 秘密','a big secret'],
    ['grammar','/ˈɡræmə(r)/','n. 语法','English grammar'],
    ['repeat','/rɪˈpiːt/','v. 重复','Repeat after me.'],
    ['note','/nəʊt/','n. 笔记','take a note'],
    ['pal','/pæl/','n. 朋友','a pen pal'],
    ['physics','/ˈfɪzɪks/','n. 物理','I like physics.'],
    ['chemistry','/ˈkemɪstri/','n. 化学','Chemistry is fun.'],
    ['memorize','/ˈmeməraɪz/','v. 记忆','Memorize the words.'],
    ['pattern','/ˈpætn/','n. 模式','a word pattern'],
    ['pronunciation','/prəˌnʌnsiˈeɪʃn/','n. 发音','good pronunciation'],
    ['increase','/ɪnˈkriːs/','v. 增加','increase speed'],
    ['speed','/spiːd/','n. 速度','at high speed'],
    ['partner','/ˈpɑːtnə(r)/','n. 同伴','a study partner'],
    ['born','/bɔːn/','adj. 天生的','a born singer'],
    ['ability','/əˈbɪləti/','n. 能力','a special ability'],
    ['create','/kriˈeɪt/','v. 创造','Create a plan.'],
    ['brain','/breɪn/','n. 大脑','use your brain'],
    ['active','/ˈæktɪv/','adj. 活跃的','an active student'],
    ['attention','/əˈtenʃn/','n. 注意','pay attention'],
    ['connect','/kəˈnekt/','v. 联系','Connect ideas.'],
    ['review','/rɪˈvjuː/','v. 复习','Review the lesson.'],
    ['knowledge','/ˈnɒlɪdʒ/','n. 知识','book knowledge'],
    ['wisely','/ˈwaɪzli/','adv. 明智地','Use time wisely.'],
    ['lifelong','/ˈlaɪflɒŋ/','adj. 终身的','a lifelong habit'],
    ['mooncake','/ˈmuːnkeɪk/','n. 月饼','eat a mooncake'],
    ['lantern','/ˈlæntən/','n. 灯笼','a red lantern'],
    ['stranger','/ˈstreɪndʒə(r)/','n. 陌生人','a friendly stranger'],
    ['relative','/ˈrelətɪv/','n. 亲戚','visit relatives'],
    ['pound','/paʊnd/','n. 英镑','five pounds'],
    ['steal','/stiːl/','v. 偷','Don\'t steal.'],
    ['lay','/leɪ/','v. 放置','Lay the book down.'],
    ['dessert','/dɪˈzɜːt/','n. 甜点','a sweet dessert'],
    ['garden','/ˈɡɑːdn/','n. 花园','a small garden'],
    ['admire','/ədˈmaɪə(r)/','v. 欣赏','Admire the moon.'],
    ['tie','/taɪ/','n. 领带','a silk tie'],
    ['haunted','/ˈhɔːntɪd/','adj. 闹鬼的','a haunted house'],
    ['spider','/ˈspaɪdə(r)/','n. 蜘蛛','a small spider'],
    ['Christmas','/ˈkrɪsməs/','n. 圣诞节','Merry Christmas!'],
    ['lie','/laɪ/','v. 说谎','Don\'t lie.'],
    ['novel','/ˈnɒvl/','n. 小说','a short novel'],
    ['bookstore','/ˈbʊkstɔː(r)/','n. 书店','go to the bookstore'],
    ['pardon','/ˈpɑːdn/','v. 原谅','Pardon me?'],
    ['washroom','/ˈwɒʃruːm/','n. 洗手间','Where is the washroom?'],
    ['restroom','/ˈrestruːm/','n. 洗手间','the restroom is there'],
    ['bathroom','/ˈbɑːθruːm/','n. 浴室','in the bathroom'],
    ['stamp','/stæmp/','n. 邮票','a Chinese stamp'],
    ['postcard','/ˈpəʊstkɑːd/','n. 明信片','send a postcard'],
    ['rush','/rʌʃ/','v. 冲','Don\'t rush.'],
    ['suggest','/səˈdʒest/','v. 建议','I suggest a book.'],
    ['polite','/pəˈlaɪt/','adj. 有礼貌的','Be polite.'],
    ['request','/rɪˈkwest/','n. 请求','a polite request'],
    ['direction','/dəˈrekʃn/','n. 方向','the right direction'],
    ['correct','/kəˈrekt/','adj. 正确的','a correct answer'],
    ['politely','/pəˈlaɪtli/','adv. 礼貌地','speak politely'],
    ['direct','/dəˈrekt/','adj. 直接的','a direct way'],
    ['speaker','/ˈspiːkə(r)/','n. 讲（某种语言）的人','an English speaker'],
    ['whom','/huːm/','pron. 谁','Whom do you like?'],
    ['impolite','/ˌɪmpəˈlaɪt/','adj. 不礼貌的','That is impolite.'],
    ['address','/əˈdres/','n. 地址','What is your address?'],
    ['underground','/ˈʌndəɡraʊnd/','adj. 地下的','the underground train'],
    ['course','/kɔːs/','n. 课程','a short course'],
    ['Italian','/ɪˈtæliən/','adj. 意大利的','Italian food'],
    ['pizza','/ˈpiːtsə/','n. 披萨','a pizza for dinner'],
    ['corner','/ˈkɔːnə(r)/','n. 角落','at the corner'],
    ['humorous','/ˈhjuːmərəs/','adj. 幽默的','a humorous teacher'],
    ['silent','/ˈsaɪlənt/','adj. 沉默的','Keep silent.'],
    ['helpful','/ˈhelpfl/','adj. 有用的','a helpful boy'],
    ['score','/skɔː(r)/','n. 得分','a high score'],
    ['background','/ˈbækɡraʊnd/','n. 背景','family background'],
    ['interview','/ˈɪntəvjuː/','n. 采访','a job interview'],
    ['Asian','/ˈeɪʃn/','adj. 亚洲的','Asian culture'],
    ['deal','/diːl/','v. 对付','Deal with it.'],
    ['shy','/ʃaɪ/','adj. 害羞的','a shy smile'],
    ['crowded','/ˈkraʊdɪd/','adj. 拥挤的','a crowded bus'],
    ['ton','/tʌn/','n. 吨','tons of books'],
    ['guard','/ɡɑːd/','n. 守卫','a security guard'],
    ['requirement','/rɪˈkwaɪəmənt/','n. 要求','meet a requirement'],
    ['influence','/ˈɪnfluəns/','v. 影响','Music influences me.'],
    ['absent','/ˈæbsənt/','adj. 缺席的','He is absent.'],
    ['fail','/feɪl/','v. 失败','Don\'t fail the test.'],
    ['examination','/ɪɡˌzæmɪˈneɪʃn/','n. 考试','a final examination'],
    ['exactly','/ɪɡˈzæktli/','adv. 确切地','Exactly right.'],
    ['pride','/praɪd/','n. 自豪','a sense of pride'],
    ['proud','/praʊd/','adj. 自豪的','I am proud of you.'],
    ['general','/ˈdʒenrəl/','adj. 总的','in general'],
    ['introduction','/ˌɪntrəˈdʌkʃn/','n. 介绍','a brief introduction'],
    ['influential','/ˌɪnfluˈenʃl/','adj. 有影响的','an influential book'],
    ['seldom','/ˈseldəm/','adv. 很少','I seldom watch TV.'],
    ['influence','/ˈɪnfluəns/','n. 影响','a good influence']
  ],
  '9下': [
    ['survey','/ˈsɜːveɪ/','n. 调查','do a survey'],
    ['standard','/ˈstændəd/','n. 标准','a high standard'],
    ['row','/rəʊ/','n. 一排','in a row'],
    ['keyboard','/ˈkiːbɔːd/','n. 键盘','a computer keyboard'],
    ['method','/ˈmeθəd/','n. 方法','a good method'],
    ['instruction','/ɪnˈstrʌkʃn/','n. 指示','follow the instruction'],
    ['double','/ˈdʌbl/','v. 加倍','double the number'],
    ['shall','/ʃæl/','aux. 将要','Shall we go?'],
    ['overcome','/ˌəʊvəˈkʌm/','v. 克服','Overcome the difficulty.'],
    ['grade','/ɡreɪd/','n. 成绩','get a good grade'],
    ['caring','/ˈkeərɪŋ/','adj. 体贴的','a caring friend'],
    ['senior','/ˈsiːniə(r)/','adj. 高年级的','a senior student'],
    ['text','/tekst/','n. 课文','read the text'],
    ['level','/ˈlevl/','n. 水平','a high level'],
    ['degree','/dɪˈɡriː/','n. 学位','a college degree'],
    ['manager','/ˈmænɪdʒə(r)/','n. 经理','a hotel manager'],
    ['believe','/bɪˈliːv/','v. 相信','I believe you.'],
    ['gentleman','/ˈdʒentlmən/','n. 先生','a true gentleman'],
    ['task','/tɑːsk/','n. 任务','a hard task'],
    ['wing','/wɪŋ/','n. 翅膀','a bird\'s wing'],
    ['literature','/ˈlɪtrətʃə(r)/','n. 文学','Chinese literature'],
    ['truck','/trʌk/','n. 卡车','a big truck'],
    ['rabbit','/ˈræbɪt/','n. 兔','a white rabbit'],
    ['attend','/əˈtend/','v. 出席','Attend the meeting.'],
    ['pink','/pɪŋk/','adj. 粉红的','a pink dress'],
    ['pocket','/ˈpɒkɪt/','n. 口袋','a small pocket'],
    ['suit','/suːt/','n. 西服','a blue suit'],
    ['express','/ɪkˈspres/','v. 表达','Express your idea.'],
    ['circle','/ˈsɜːkl/','n. 圈','draw a circle'],
    ['victory','/ˈvɪktəri/','n. 胜利','a big victory'],
    ['lead','/liːd/','v. 领导','Lead the team.'],
    ['position','/pəˈzɪʃn/','n. 位置','a good position'],
    ['enemy','/ˈenəmi/','n. 敌人','defeat the enemy'],
    ['period','/ˈpɪəriəd/','n. 时期','a difficult period'],
    ['stone','/stəʊn/','n. 石头','a small stone'],
    ['shoot','/ʃuːt/','v. 射击','Shoot the ball.'],
    ['god','/ɡɒd/','n. 神','a Greek god'],
    ['remind','/rɪˈmaɪnd/','v. 提醒','Remind me, please.'],
    ['bit','/bɪt/','n. 一点','a bit of water'],
    ['silly','/ˈsɪli/','adj. 愚蠢的','a silly mistake'],
    ['hide','/haɪd/','v. 隐藏','Hide the gift.'],
    ['magic','/ˈmædʒɪk/','adj. 有魔力的','a magic stone'],
    ['stick','/stɪk/','n. 棍','a long stick'],
    ['tail','/teɪl/','n. 尾巴','a dog\'s tail'],
    ['western','/ˈwestən/','adj. 西方的','western food'],
    ['stepsister','/ˈstepsɪstə(r)/','n. 继姐妹','the evil stepsister'],
    ['prince','/prɪns/','n. 王子','a young prince'],
    ['couple','/ˈkʌpl/','n. 夫妻','a happy couple'],
    ['smile','/smaɪl/','v. 微笑','She smiles at me.'],
    ['fall in love','/fɔːl ɪn lʌv/','phr. 爱上','fall in love with him'],
    ['fit','/fɪt/','v. 适合','The dress fits her.'],
    ['gold','/ɡəʊld/','n. 金子','a gold ring'],
    ['silk','/sɪlk/','n. 丝绸','a silk scarf'],
    ['nobody','/ˈnəʊbədi/','pron. 没有人','Nobody is here.'],
    ['cheat','/tʃiːt/','v. 欺骗','Don\'t cheat.'],
    ['emperor','/ˈempərə(r)/','n. 皇帝','the Chinese emperor'],
    ['underwear','/ˈʌndəweə(r)/','n. 内衣','a piece of underwear'],
    ['stupid','/ˈstjuːpɪd/','adj. 愚蠢的','a stupid idea'],
    ['wave','/weɪv/','n. 波浪','a big wave'],
    ['scene','/siːn/','n. 场景','a sad scene'],
    ['earthquake','/ˈɜːθkweɪk/','n. 地震','a strong earthquake'],
    ['voice','/vɔɪs/','n. 声音','a loud voice'],
    ['object','/ˈɒbdʒɪkt/','n. 物体','a small object'],
    ['recently','/ˈriːsntli/','adv. 最近','I saw him recently.'],
    ['cheat','/tʃiːt/','v. 作弊','cheat in a test']
  ]
};

const VOL_ORDER = ['7上','7下','8上','8下','9上','9下'];
const MARKER = '          words: [';  // 10 空格缩进，避开 userWords

function buildWords(arr){
  return '[\n' + arr.map(w =>
    '            { word:"' + w[0] + '", phonetic:"' + w[1] + '", meaning:"' + w[2] + '", example:"' + w[3] + '" }'
  ).join(',\n') + '\n          ]';
}

// 1) 在原始 html 中找出全部 6 个 words 数组的 [idx,end]
const positions = [];
let from = 0;
while (true) {
  const idx = html.indexOf(MARKER, from);
  if (idx < 0) break;
  let depth = 0, end = -1;
  for (let i = idx + MARKER.length - 1; i < html.length; i++) {
    if (html[i] === '[') depth++;
    else if (html[i] === ']') { depth--; if (depth === 0) { end = i; break; } }
  }
  if (end < 0) { console.error('未找到匹配的 ]'); break; }
  positions.push({ idx, end });
  from = end + 1;
}
if (positions.length !== 6) { console.error('words 数组数量异常:', positions.length); process.exit(1); }

// 2) 从后往前替换（避免前面的索引因插入而偏移）
let replaced = 0;
for (let i = positions.length - 1; i >= 0; i--) {
  const vol = VOL_ORDER[i];
  const arr = WORDS[vol];
  const { idx, end } = positions[i];
  const before = html.slice(0, idx);
  const after = html.slice(end + 1);
  html = before + 'words: ' + buildWords(arr) + after;
  console.log(vol, '→', arr.length, '词');
  replaced++;
}
fs.writeFileSync(path, html);
console.log('已替换', replaced, '册 words 数组');
